export function createLiveControllerOptions({
  app,
  liveDebug,
  liveDebugDiagnostics,
  sourceFirstMode = true,
  config = {},
  normalizeLogString,
  liveRuntimeHelpers,
  resolveActivationBlockBounds,
  resolveLiveBlockSelection,
  findBlockContainingPosition,
  findNearestBlockForPosition,
  isFencedCodeBlock,
  parseSourceFromAttribute,
  shouldPreferRenderedDomAnchorPosition,
  shouldPreferSourceFromForRenderedFencedClick,
  shouldPreferSourceFromForRenderedBoundaryClick,
  isRefreshEffect,
  renderPreview,
  updateActionButtons,
  setStatus,
  scheduleAutosave,
  readDocumentModel,
  windowObject,
  documentObject,
  requestAnimationFrameFn,
  createCursorSelection,
  transactionUserEventAnnotation,
  performanceObserverClass,
  elementConstructor,
  nodeConstructor,
  nowFn
} = {}) {
  return {
    app,
    liveDebug,
    liveDebugDiagnostics,
    sourceFirstMode,
    config,
    helpers: {
      normalizeLogString,
      readLineInfoForPosition: liveRuntimeHelpers.readLineInfoForPosition,
      clampNumber: liveRuntimeHelpers.clampNumber,
      readBlockLineBoundsForLog: liveRuntimeHelpers.readBlockLineBoundsForLog,
      buildCoordSamples: liveRuntimeHelpers.buildCoordSamples,
      resolvePointerPosition: liveRuntimeHelpers.resolvePointerPosition,
      summarizeRectForLog: liveRuntimeHelpers.summarizeRectForLog,
      readComputedStyleSnapshotForLog: liveRuntimeHelpers.readComputedStyleSnapshotForLog,
      liveBlocksForView: liveRuntimeHelpers.liveBlocksForView,
      normalizePointerTarget: liveRuntimeHelpers.normalizePointerTarget,
      readPointerCoordinates: liveRuntimeHelpers.readPointerCoordinates,
      describeElementForLog: liveRuntimeHelpers.describeElementForLog,
      recordInputSignal: liveRuntimeHelpers.recordInputSignal,
      resolveActivationBlockBounds,
      resolveLiveBlockSelection,
      findBlockContainingPosition,
      findNearestBlockForPosition,
      isFencedCodeBlock,
      parseSourceFromAttribute,
      findRenderedSourceRangeTarget: liveRuntimeHelpers.findRenderedSourceRangeTarget,
      resolvePositionFromRenderedSourceRange: liveRuntimeHelpers.resolvePositionFromRenderedSourceRange,
      distanceToBlockBounds: liveRuntimeHelpers.distanceToBlockBounds,
      shouldPreferRenderedDomAnchorPosition,
      shouldPreferSourceFromForRenderedFencedClick,
      shouldPreferSourceFromForRenderedBoundaryClick,
      buildRenderedPointerProbe: liveRuntimeHelpers.buildRenderedPointerProbe,
      summarizeLineNumbersForCoordSamples: liveRuntimeHelpers.summarizeLineNumbersForCoordSamples,
      readCursorVisibilityForLog: liveRuntimeHelpers.readCursorVisibilityForLog,
      readDomSelectionForLog: liveRuntimeHelpers.readDomSelectionForLog,
      readGutterVisibilityForLog: liveRuntimeHelpers.readGutterVisibilityForLog,
      requestLivePreviewRefresh: liveRuntimeHelpers.requestLivePreviewRefresh,
      captureLiveDebugSnapshot: liveRuntimeHelpers.captureLiveDebugSnapshot,
      scheduleCursorVisibilityProbe: liveRuntimeHelpers.scheduleCursorVisibilityProbe,
      isCursorVisibilitySuspect: liveRuntimeHelpers.isCursorVisibilitySuspect,
      moveLiveCursorVertically: liveRuntimeHelpers.moveLiveCursorVertically,
      readRecentInputSignal: liveRuntimeHelpers.readRecentInputSignal,
      liveSourceMapIndexForView: liveRuntimeHelpers.liveSourceMapIndexForView,
      emitFenceVisibilityState: liveRuntimeHelpers.emitFenceVisibilityState,
      isRefreshEffect,
      renderPreview,
      updateActionButtons,
      setStatus,
      scheduleAutosave,
      readDocumentModel
    },
    runtime: {
      windowObject,
      documentObject,
      requestAnimationFrameFn,
      createCursorSelection,
      transactionUserEventAnnotation,
      performanceObserverClass,
      elementConstructor,
      nodeConstructor,
      nowFn
    }
  };
}
