export function createLiveControllerOptions({
  app,
  liveDebug,
  liveDebugDiagnostics,
  config = {},
  normalizeLogString,
  liveRuntimeHelpers,
  resolveActivationBlockBounds,
  isRefreshEffect,
  renderPreview,
  updateActionButtons,
  setStatus,
  scheduleAutosave,
  readDocumentModel,
  windowObject,
  documentObject,
  requestAnimationFrameFn,
  createCursorSelection,
  transactionUserEventAnnotation,
  performanceObserverClass,
  elementConstructor,
  nodeConstructor,
  nowFn
} = {}) {
  return {
    app,
    liveDebug,
    liveDebugDiagnostics,
    config,
    helpers: {
      normalizeLogString,
      readLineInfoForPosition: liveRuntimeHelpers.readLineInfoForPosition,
      readBlockLineBoundsForLog: liveRuntimeHelpers.readBlockLineBoundsForLog,
      resolvePointerPosition: liveRuntimeHelpers.resolvePointerPosition,
      liveBlocksForView: liveRuntimeHelpers.liveBlocksForView,
      normalizePointerTarget: liveRuntimeHelpers.normalizePointerTarget,
      readPointerCoordinates: liveRuntimeHelpers.readPointerCoordinates,
      describeElementForLog: liveRuntimeHelpers.describeElementForLog,
      recordInputSignal: liveRuntimeHelpers.recordInputSignal,
      resolveActivationBlockBounds,
      readCursorVisibilityForLog: liveRuntimeHelpers.readCursorVisibilityForLog,
      readDomSelectionForLog: liveRuntimeHelpers.readDomSelectionForLog,
      readGutterVisibilityForLog: liveRuntimeHelpers.readGutterVisibilityForLog,
      requestLivePreviewRefresh: liveRuntimeHelpers.requestLivePreviewRefresh,
      captureLiveDebugSnapshot: liveRuntimeHelpers.captureLiveDebugSnapshot,
      scheduleCursorVisibilityProbe: liveRuntimeHelpers.scheduleCursorVisibilityProbe,
      isCursorVisibilitySuspect: liveRuntimeHelpers.isCursorVisibilitySuspect,
      moveLiveCursorVertically: liveRuntimeHelpers.moveLiveCursorVertically,
      readRecentInputSignal: liveRuntimeHelpers.readRecentInputSignal,
      liveSourceMapIndexForView: liveRuntimeHelpers.liveSourceMapIndexForView,
      emitFenceVisibilityState: liveRuntimeHelpers.emitFenceVisibilityState,
      isRefreshEffect,
      renderPreview,
      updateActionButtons,
      setStatus,
      scheduleAutosave,
      readDocumentModel
    },
    runtime: {
      windowObject,
      documentObject,
      requestAnimationFrameFn,
      createCursorSelection,
      transactionUserEventAnnotation,
      performanceObserverClass,
      elementConstructor,
      nodeConstructor,
      nowFn
    }
  };
}
