export const LAUNCHER_HEARTBEAT_MS = 4000;
export const LIVE_DEBUG_UPLOAD_DEBOUNCE_MS = 900;
export const LIVE_DEBUG_UPLOAD_MAX_BATCH = 200;
export const LIVE_DEBUG_UPLOAD_MAX_QUEUE = 4000;
export const LIVE_PREVIEW_FRAGMENT_CACHE_MAX = 2500;
export const LIVE_PREVIEW_SLOW_BUILD_WARN_MS = 12;
export const LIVE_PREVIEW_VIEWPORT_LINE_BUFFER = 8;
export const LIVE_PREVIEW_VIEWPORT_MINIMUM_LINE_SPAN = 24;
export const LIVE_PREVIEW_MAX_VIEWPORT_BLOCKS = 160;
export const LIVE_PREVIEW_MAX_VIEWPORT_CHARACTERS = 24000;
export const LIVE_DEBUG_INPUT_TTL_MS = 900;
export const LIVE_DEBUG_SELECTION_JUMP_WARN_LINE_DELTA = 20;
export const LIVE_DEBUG_SELECTION_JUMP_WARN_POS_DELTA = 80;
export const LIVE_DEBUG_SELECTION_JUMP_SUPPRESS_AFTER_PROGRAMMATIC_MS = 900;
export const LIVE_DEBUG_DOM_SELECTION_THROTTLE_MS = 120;
export const LIVE_DEBUG_CURSOR_PROBE_THROTTLE_MS = 100;
export const LIVE_DEBUG_GUTTER_PROBE_THROTTLE_MS = 220;
export const LIVE_DEBUG_CURSOR_ACTIVE_LINE_MISSING_THROTTLE_MS = 220;
export const LIVE_DEBUG_CURSOR_RECOVERY_COOLDOWN_MS = 260;
export const LIVE_DEBUG_CURSOR_MAX_EXPECTED_HEIGHT_PX = 42;
export const LIVE_DEBUG_CURSOR_MAX_EXPECTED_WIDTH_PX = 6;
export const LIVE_DEBUG_CURSOR_RIGHT_DRIFT_PX = 12;
export const LIVE_DEBUG_CURSOR_TRANSIENT_DRIFT_DELTA_PX = 80;
export const LIVE_DEBUG_BLOCK_MAP_LARGE_DELTA_POS = 20;
export const LIVE_DEBUG_BLOCK_MAP_LARGE_DELTA_LINES = 2;
export const LIVE_PREVIEW_RENDERED_FENCED_STICKY_MAX_POS_DELTA = 12;
export const LIVE_PREVIEW_RENDERED_FENCED_STICKY_MAX_LINE_DELTA = 2;
export const LIVE_PREVIEW_RENDERED_BOUNDARY_STICKY_MAX_POS_DELTA = 30;
export const LIVE_PREVIEW_RENDERED_BOUNDARY_STICKY_MAX_LINE_DELTA = 3;
export const LIVE_PREVIEW_RENDERED_BOUNDARY_STICKY_MAX_DISTANCE_FROM_BOTTOM_PX = 14;
export const LIVE_PREVIEW_RENDERED_BOUNDARY_STICKY_MIN_RATIO_Y = 0.3;
export const LIVE_PREVIEW_RENDERED_DOM_ANCHOR_STICKY_MAX_POS_DELTA = 40;

export const NAVIGATION_KEYS = new Set([
  'ArrowUp',
  'ArrowDown',
  'ArrowLeft',
  'ArrowRight',
  'Home',
  'End',
  'PageUp',
  'PageDown'
]);

export const LIVE_DEBUG_KEYLOG_KEYS = new Set([
  ...NAVIGATION_KEYS,
  'Enter',
  'Tab',
  'Backspace',
  'Delete',
  'Escape'
]);
